import React, { useState, useRef, useEffect } from 'react';
import {
  Search,
  Clock,
  Smile,
  PawPrint,
  Apple,
  Trophy,
  Palmtree,
  Lightbulb,
  AtSign,
  Flag,
  X,
} from 'lucide-react';

const DEFAULT_RECENT = [
  '🥺', '🥹', '🥰', '😍', '💗', '😘', '😊',
  '🔥', '✨', '👍', '🎉', '❤️', '🛍️', '🎁', '👶', '🍼'
];

const EMOJI_CATEGORIES = [
  {
    id: 'recent',
    title: 'Recently Used',
    icon: Clock,
    emojis: [
      { char: '🥺', tags: ['pleading', 'puppy', 'eyes', 'cute'] },
      { char: '🥹', tags: ['tear', 'holding back', 'happy', 'grateful'] },
      { char: '🥰', tags: ['love', 'hearts', 'smile', 'affection'] },
      { char: '😍', tags: ['heart eyes', 'love', 'crush', 'adorable'] },
      { char: '💗', tags: ['pink heart', 'growing heart', 'love'] },
      { char: '😘', tags: ['blow kiss', 'love', 'flirt'] },
      { char: '😊', tags: ['blush', 'happy', 'warm', 'friendly'] },
      { char: '🔥', tags: ['fire', 'hot', 'lit', 'deal'] },
      { char: '✨', tags: ['sparkles', 'magic', 'shine', 'special'] },
      { char: '👍', tags: ['thumbs up', 'like', 'agree', 'good'] },
      { char: '🎉', tags: ['tada', 'party', 'celebrate', 'congrats'] },
      { char: '❤️', tags: ['red heart', 'love', 'care'] },
      { char: '🛍️', tags: ['shopping bags', 'store', 'sale', 'buy'] },
      { char: '🎁', tags: ['gift', 'present', 'reward', 'giveaway'] },
      { char: '👶', tags: ['baby', 'child', 'mom', 'kid'] },
      { char: '🍼', tags: ['bottle', 'milk', 'baby', 'feeding'] },
    ],
  },
  {
    id: 'smileys',
    title: 'Smileys & People',
    icon: Smile,
    emojis: [
      { char: '😀', tags: ['grinning', 'happy'] },
      { char: '😃', tags: ['big eyes', 'smile', 'glad'] },
      { char: '😄', tags: ['laughing', 'joy', 'smile'] },
      { char: '😁', tags: ['beaming', 'teeth', 'smile'] },
      { char: '😆', tags: ['squint', 'laugh', 'giggle'] },
      { char: '🥹', tags: ['emotional', 'grateful', 'proud'] },
      { char: '😅', tags: ['sweat smile', 'relief', 'phew'] },
      { char: '😂', tags: ['joy', 'tears of laughter', 'lol'] },
      { char: '🤣', tags: ['rofl', 'rolling on floor laughing'] },
      { char: '🥲', tags: ['smiling tear', 'proud', 'bittersweet'] },
      { char: '☺️', tags: ['warm smile', 'relaxed'] },
      { char: '😊', tags: ['blush', 'kind'] },
      { char: '😇', tags: ['halo', 'angel', 'innocent'] },
      { char: '🙂', tags: ['slightly smiling', 'okay'] },
      { char: '🙃', tags: ['upside down', 'silly', 'irony'] },
      { char: '😉', tags: ['wink', 'playful'] },
      { char: '😌', tags: ['relieved', 'peaceful'] },
      { char: '😍', tags: ['heart eyes', 'love'] },
      { char: '🥰', tags: ['three hearts', 'in love'] },
      { char: '😘', tags: ['kiss', 'heart'] },
      { char: '😗', tags: ['kissing face'] },
      { char: '😙', tags: ['kissing smile'] },
      { char: '😚', tags: ['closed eyes kiss'] },
      { char: '😋', tags: ['yum', 'delicious', 'tasty'] },
      { char: '😛', tags: ['tongue out'] },
      { char: '😝', tags: ['squint tongue'] },
      { char: '😜', tags: ['wink tongue'] },
      { char: '🤪', tags: ['zany', 'goofy', 'crazy'] },
      { char: '🤨', tags: ['raised eyebrow', 'skeptical'] },
      { char: '🧐', tags: ['monocle', 'curious', 'inspecting'] },
      { char: '🤓', tags: ['nerd', 'glasses'] },
      { char: '😎', tags: ['sunglasses', 'cool'] },
      { char: '🥳', tags: ['party hat', 'celebration'] },
      { char: '🤩', tags: ['star eyes', 'impressed', 'wow'] },
      { char: '😏', tags: ['smirk', 'suggestive'] },
      { char: '😒', tags: ['unamused', 'bored'] },
      { char: '😞', tags: ['disappointed'] },
      { char: '😔', tags: ['pensive', 'sad'] },
      { char: '😟', tags: ['worried'] },
      { char: '😕', tags: ['confused'] },
      { char: '🙁', tags: ['slightly frowning'] },
      { char: '😣', tags: ['persevering'] },
      { char: '😖', tags: ['confounded'] },
      { char: '😫', tags: ['tired', 'frustrated'] },
      { char: '😩', tags: ['weary'] },
      { char: '🥺', tags: ['pleading', 'begging'] },
      { char: '😢', tags: ['crying', 'tear'] },
      { char: '😭', tags: ['loudly crying', 'sobbing'] },
      { char: '😤', tags: ['triumph', 'proud'] },
      { char: '😠', tags: ['angry', 'mad'] },
      { char: '😡', tags: ['pouting', 'rage'] },
      { char: '🤬', tags: ['cursing', 'swearing'] },
      { char: '🤯', tags: ['mind blown', 'exploding head'] },
      { char: '😳', tags: ['flushed', 'shocked'] },
      { char: '🥵', tags: ['hot face', 'heat'] },
      { char: '🥶', tags: ['cold face', 'freezing'] },
      { char: '😱', tags: ['screaming', 'scared', 'fear'] },
      { char: '😨', tags: ['fearful', 'nervous'] },
      { char: '😰', tags: ['anxious with sweat'] },
      { char: '😥', tags: ['sad relieved'] },
      { char: '😓', tags: ['downcast sweat'] },
      { char: '🤗', tags: ['hugging', 'warm'] },
      { char: '🤔', tags: ['thinking', 'wondering'] },
      { char: '🫣', tags: ['peeking eye'] },
      { char: '🤭', tags: ['hand over mouth', 'giggle'] },
      { char: '🤫', tags: ['shushing', 'quiet', 'secret'] },
      { char: '🤥', tags: ['lying', 'pinocchio'] },
      { char: '😶', tags: ['no mouth', 'silent'] },
      { char: '😐', tags: ['neutral face'] },
      { char: '😑', tags: ['expressionless'] },
      { char: '😬', tags: ['grimacing'] },
      { char: '🙄', tags: ['eye roll', 'whatever'] },
      { char: '😯', tags: ['surprised', 'hushed'] },
      { char: '😦', tags: ['frowning open mouth'] },
      { char: '😮', tags: ['open mouth', 'gasp'] },
      { char: '😲', tags: ['astonished'] },
      { char: '🥱', tags: ['yawning', 'sleepy'] },
      { char: '😴', tags: ['sleeping', 'zzz'] },
      { char: '🤤', tags: ['drooling'] },
      { char: '😪', tags: ['sleepy tear'] },
      { char: '😵', tags: ['dizzy'] },
      { char: '🤐', tags: ['zipper mouth'] },
      { char: '🥴', tags: ['woozy', 'drunk'] },
      { char: '🤢', tags: ['nauseated'] },
      { char: '🤮', tags: ['vomiting'] },
      { char: '🤧', tags: ['sneezing'] },
      { char: '😷', tags: ['medical mask'] },
      { char: '🤒', tags: ['thermometer', 'sick'] },
      { char: '🤕', tags: ['head bandage', 'hurt'] },
      { char: '🤑', tags: ['money mouth', 'rich'] },
      { char: '🤠', tags: ['cowboy'] },
      { char: '😈', tags: ['smiling devil'] },
      { char: '👿', tags: ['angry devil'] },
      { char: '👹', tags: ['ogre'] },
      { char: '👺', tags: ['goblin'] },
      { char: '🤡', tags: ['clown'] },
      { char: '💩', tags: ['poop', 'poo'] },
      { char: '👻', tags: ['ghost', 'boo'] },
      { char: '💀', tags: ['skull', 'dead'] },
      { char: '☠️', tags: ['skull and crossbones'] },
      { char: '👽', tags: ['alien'] },
      { char: '👾', tags: ['alien monster'] },
      { char: '🤖', tags: ['robot'] },
      { char: '👋', tags: ['waving hand', 'hello', 'bye'] },
      { char: '🤚', tags: ['raised back of hand'] },
      { char: '🖐️', tags: ['fingers splayed'] },
      { char: '✋', tags: ['raised hand', 'stop', 'high five'] },
      { char: '🖖', tags: ['vulcan salute'] },
      { char: '👌', tags: ['ok hand', 'perfect', 'fine'] },
      { char: '🤌', tags: ['pinched fingers', 'italian'] },
      { char: '🤏', tags: ['pinching hand', 'small', 'little'] },
      { char: '✌️', tags: ['peace sign', 'victory'] },
      { char: '🤞', tags: ['crossed fingers', 'good luck', 'hope'] },
      { char: '🫰', tags: ['hand with index and thumb crossed', 'finger heart'] },
      { char: '🤟', tags: ['love you gesture'] },
      { char: '🤘', tags: ['rock on', 'horns'] },
      { char: '🤙', tags: ['call me', 'shaka'] },
      { char: '👈', tags: ['point left'] },
      { char: '👉', tags: ['point right'] },
      { char: '👆', tags: ['point up'] },
      { char: '🖕', tags: ['middle finger'] },
      { char: '👇', tags: ['point down'] },
      { char: '☝️', tags: ['index pointing up'] },
      { char: '👍', tags: ['thumbs up', 'like', 'agree'] },
      { char: '👎', tags: ['thumbs down', 'dislike'] },
      { char: '✊', tags: ['fist', 'power'] },
      { char: '👊', tags: ['punch', 'fist bump'] },
      { char: '🤛', tags: ['left fist'] },
      { char: '🤜', tags: ['right fist'] },
      { char: '👏', tags: ['clapping hands', 'bravo'] },
      { char: '🙌', tags: ['raising hands', 'celebrate'] },
      { char: '🫶', tags: ['heart hands', 'love'] },
      { char: '👐', tags: ['open hands'] },
      { char: '🤲', tags: ['palms up together', 'prayer'] },
      { char: '🤝', tags: ['handshake', 'deal', 'agreement'] },
      { char: '🙏', tags: ['folded hands', 'thank you', 'please'] },
      { char: '💪', tags: ['flexed biceps', 'strong'] },
    ],
  },
  {
    id: 'animals',
    title: 'Animals & Nature',
    icon: PawPrint,
    emojis: [
      { char: '🐶', tags: ['dog', 'puppy'] },
      { char: '🐱', tags: ['cat', 'kitten'] },
      { char: '🐭', tags: ['mouse'] },
      { char: '🐹', tags: ['hamster'] },
      { char: '🐰', tags: ['rabbit', 'bunny'] },
      { char: '🦊', tags: ['fox'] },
      { char: '🐻', tags: ['bear'] },
      { char: '🐼', tags: ['panda'] },
      { char: '🐨', tags: ['koala'] },
      { char: '🐯', tags: ['tiger'] },
      { char: '🦁', tags: ['lion'] },
      { char: '🐮', tags: ['cow'] },
      { char: '🐷', tags: ['pig'] },
      { char: '🐸', tags: ['frog'] },
      { char: '🐵', tags: ['monkey'] },
      { char: '🐔', tags: ['chicken'] },
      { char: '🐧', tags: ['penguin'] },
      { char: '🐦', tags: ['bird'] },
      { char: '🦆', tags: ['duck'] },
      { char: '🦅', tags: ['eagle'] },
      { char: '🦉', tags: ['owl'] },
      { char: '🦇', tags: ['bat'] },
      { char: '🐺', tags: ['wolf'] },
      { char: '🐗', tags: ['boar'] },
      { char: '🐴', tags: ['horse'] },
      { char: '🦄', tags: ['unicorn'] },
      { char: '🐝', tags: ['bee'] },
      { char: '🐛', tags: ['caterpillar'] },
      { char: '🦋', tags: ['butterfly'] },
      { char: '🐌', tags: ['snail'] },
      { char: '🐞', tags: ['ladybug'] },
      { char: '🐢', tags: ['turtle'] },
      { char: '🐍', tags: ['snake'] },
      { char: '🐙', tags: ['octopus'] },
      { char: '🦑', tags: ['squid'] },
      { char: '🦐', tags: ['shrimp'] },
      { char: '🦀', tags: ['crab'] },
      { char: '🐡', tags: ['blowfish'] },
      { char: '🐠', tags: ['tropical fish'] },
      { char: '🐟', tags: ['fish'] },
      { char: '🐬', tags: ['dolphin'] },
      { char: '🐳', tags: ['spouting whale'] },
      { char: '🐋', tags: ['whale'] },
      { char: '🦈', tags: ['shark'] },
      { char: '🌸', tags: ['cherry blossom', 'flower'] },
      { char: '💮', tags: ['white flower'] },
      { char: '🏵️', tags: ['rosette'] },
      { char: '🌹', tags: ['rose'] },
      { char: '🥀', tags: ['wilted flower'] },
      { char: '🌺', tags: ['hibiscus'] },
      { char: '🌻', tags: ['sunflower'] },
      { char: '🌼', tags: ['blossom'] },
      { char: '🌷', tags: ['tulip'] },
      { char: '🌱', tags: ['seedling'] },
      { char: '🪴', tags: ['potted plant'] },
      { char: '🌲', tags: ['evergreen tree'] },
      { char: '🌳', tags: ['deciduous tree'] },
      { char: '🌴', tags: ['palm tree'] },
      { char: '🌵', tags: ['cactus'] },
      { char: '🌾', tags: ['sheaf of rice'] },
      { char: '🌿', tags: ['herb'] },
      { char: '☘️', tags: ['shamrock'] },
      { char: '🍀', tags: ['four leaf clover', 'luck'] },
      { char: '🍁', tags: ['maple leaf'] },
      { char: '🍂', tags: ['fallen leaf'] },
      { char: '🍃', tags: ['leaf fluttering in wind'] },
    ],
  },
  {
    id: 'food',
    title: 'Food & Drink',
    icon: Apple,
    emojis: [
      { char: '🍎', tags: ['red apple'] },
      { char: '🍏', tags: ['green apple'] },
      { char: '🍐', tags: ['pear'] },
      { char: '🍊', tags: ['tangerine', 'orange'] },
      { char: '🍋', tags: ['lemon'] },
      { char: '🍌', tags: ['banana'] },
      { char: '🍉', tags: ['watermelon'] },
      { char: '🍇', tags: ['grapes'] },
      { char: '🍓', tags: ['strawberry'] },
      { char: '🫐', tags: ['blueberries'] },
      { char: '🍈', tags: ['melon'] },
      { char: '🍒', tags: ['cherries'] },
      { char: '🍑', tags: ['peach'] },
      { char: '🥭', tags: ['mango'] },
      { char: '🍍', tags: ['pineapple'] },
      { char: '🥥', tags: ['coconut'] },
      { char: '🥝', tags: ['kiwi'] },
      { char: '🍅', tags: ['tomato'] },
      { char: '🍆', tags: ['eggplant'] },
      { char: '🥑', tags: ['avocado'] },
      { char: '🥦', tags: ['broccoli'] },
      { char: '🥬', tags: ['leafy green'] },
      { char: '🥒', tags: ['cucumber'] },
      { char: '🌶️', tags: ['hot pepper', 'spicy'] },
      { char: '🌽', tags: ['corn'] },
      { char: '🥕', tags: ['carrot'] },
      { char: '🥔', tags: ['potato'] },
      { char: '🥐', tags: ['croissant'] },
      { char: '🥯', tags: ['bagel'] },
      { char: '🍞', tags: ['bread'] },
      { char: '🥖', tags: ['baguette'] },
      { char: '🧀', tags: ['cheese'] },
      { char: '🥚', tags: ['egg'] },
      { char: '🍳', tags: ['cooking', 'fried egg'] },
      { char: '🥞', tags: ['pancakes'] },
      { char: '🧇', tags: ['waffle'] },
      { char: '🥓', tags: ['bacon'] },
      { char: '🥩', tags: ['meat'] },
      { char: '🍗', tags: ['poultry leg'] },
      { char: '🍖', tags: ['meat on bone'] },
      { char: '🌭', tags: ['hot dog'] },
      { char: '🍔', tags: ['hamburger', 'burger'] },
      { char: '🍟', tags: ['french fries'] },
      { char: '🍕', tags: ['pizza'] },
      { char: '🥪', tags: ['sandwich'] },
      { char: '🌮', tags: ['taco'] },
      { char: '🌯', tags: ['burrito'] },
      { char: '🍜', tags: ['noodles', 'ramen'] },
      { char: '🍝', tags: ['spaghetti'] },
      { char: '🍣', tags: ['sushi'] },
      { char: '🍱', tags: ['bento'] },
      { char: '🥟', tags: ['dumpling'] },
      { char: '🎂', tags: ['birthday cake'] },
      { char: '🍰', tags: ['shortcake'] },
      { char: '🧁', tags: ['cupcake'] },
      { char: '🥧', tags: ['pie'] },
      { char: '🍫', tags: ['chocolate bar'] },
      { char: '🍬', tags: ['candy'] },
      { char: '🍭', tags: ['lollipop'] },
      { char: '🍮', tags: ['custard'] },
      { char: '☕', tags: ['coffee', 'hot beverage'] },
      { char: '🧋', tags: ['boba', 'bubble tea'] },
      { char: '🍵', tags: ['tea'] },
      { char: '🧃', tags: ['juice box'] },
      { char: '🍼', tags: ['baby bottle', 'milk'] },
      { char: '🥛', tags: ['glass of milk'] },
    ],
  },
  {
    id: 'activities',
    title: 'Activities',
    icon: Trophy,
    emojis: [
      { char: '⚽', tags: ['soccer ball', 'football'] },
      { char: '🏀', tags: ['basketball'] },
      { char: '🏈', tags: ['american football'] },
      { char: '⚾', tags: ['baseball'] },
      { char: '🥎', tags: ['softball'] },
      { char: '🎾', tags: ['tennis'] },
      { char: '🏐', tags: ['volleyball'] },
      { char: '🏉', tags: ['rugby'] },
      { char: '🎱', tags: ['billiards', '8 ball'] },
      { char: '🏓', tags: ['ping pong', 'table tennis'] },
      { char: '🏸', tags: ['badminton'] },
      { char: '🥊', tags: ['boxing glove'] },
      { char: '🥋', tags: ['martial arts'] },
      { char: '⛳', tags: ['golf'] },
      { char: '⛸️', tags: ['ice skate'] },
      { char: '🎣', tags: ['fishing pole'] },
      { char: '🎯', tags: ['bullseye', 'target', 'hit'] },
      { char: '🎮', tags: ['video game', 'controller'] },
      { char: '🎲', tags: ['game die', 'dice'] },
      { char: '🧩', tags: ['puzzle piece'] },
      { char: '🏆', tags: ['trophy', 'winner', 'award'] },
      { char: '🥇', tags: ['1st place medal', 'gold'] },
      { char: '🥈', tags: ['2nd place medal', 'silver'] },
      { char: '🥉', tags: ['3rd place medal', 'bronze'] },
      { char: '🎖️', tags: ['military medal'] },
      { char: '🏵️', tags: ['rosette'] },
      { char: '🎫', tags: ['ticket'] },
      { char: '🎟️', tags: ['admission tickets'] },
      { char: '🎪', tags: ['circus tent'] },
      { char: '🎭', tags: ['performing arts', 'theater'] },
      { char: '🎨', tags: ['artist palette', 'art'] },
      { char: '🎬', tags: ['clapper board', 'movie'] },
      { char: '🎤', tags: ['microphone', 'sing'] },
      { char: '🎧', tags: ['headphones', 'music'] },
      { char: '🎼', tags: ['musical score'] },
      { char: '🎹', tags: ['musical keyboard', 'piano'] },
      { char: '🥁', tags: ['drum'] },
      { char: '🎷', tags: ['saxophone'] },
      { char: '🎺', tags: ['trumpet'] },
      { char: '🎸', tags: ['guitar'] },
      { char: '🪕', tags: ['banjo'] },
      { char: '🎻', tags: ['violin'] },
    ],
  },
  {
    id: 'travel',
    title: 'Travel & Places',
    icon: Palmtree,
    emojis: [
      { char: '🚗', tags: ['car', 'automobile'] },
      { char: '🚕', tags: ['taxi'] },
      { char: '🚙', tags: ['suv'] },
      { char: '🚌', tags: ['bus'] },
      { char: '🚎', tags: ['trolleybus'] },
      { char: '🏎️', tags: ['racing car'] },
      { char: '🚓', tags: ['police car'] },
      { char: '🚑', tags: ['ambulance'] },
      { char: '🚒', tags: ['fire engine'] },
      { char: '🚐', tags: ['minibus'] },
      { char: '🛻', tags: ['pickup truck'] },
      { char: '🚚', tags: ['delivery truck'] },
      { char: '🚛', tags: ['articulated lorry'] },
      { char: '🚜', tags: ['tractor'] },
      { char: '🛵', tags: ['motor scooter'] },
      { char: '🏍️', tags: ['motorcycle'] },
      { char: '🚲', tags: ['bicycle', 'bike'] },
      { char: '🛴', tags: ['kick scooter'] },
      { char: '🚨', tags: ['police car light', 'siren'] },
      { char: '✈️', tags: ['airplane', 'flight'] },
      { char: '🛫', tags: ['airplane departure'] },
      { char: '🛬', tags: ['airplane arrival'] },
      { char: '🚀', tags: ['rocket', 'launch', 'fast'] },
      { char: '🛸', tags: ['flying saucer', 'ufo'] },
      { char: '🚁', tags: ['helicopter'] },
      { char: '🛶', tags: ['canoe'] },
      { char: '⛵', tags: ['sailboat'] },
      { char: '🚤', tags: ['speedboat'] },
      { char: '🛳️', tags: ['passenger ship'] },
      { char: '⛴️', tags: ['ferry'] },
      { char: '🚢', tags: ['ship'] },
      { char: '⚓', tags: ['anchor'] },
      { char: '⛽', tags: ['fuel pump', 'gas'] },
      { char: '🏖️', tags: ['beach with umbrella'] },
      { char: '🏝️', tags: ['desert island'] },
      { char: '🏜️', tags: ['desert'] },
      { char: '🌋', tags: ['volcano'] },
      { char: '⛰️', tags: ['mountain'] },
      { char: '🏔️', tags: ['snow-capped mountain'] },
      { char: '🏕️', tags: ['camping'] },
      { char: '⛺', tags: ['tent'] },
      { char: '🏠', tags: ['house'] },
      { char: '🏡', tags: ['house with garden'] },
      { char: '🏢', tags: ['office building'] },
      { char: '🏣', tags: ['japanese post office'] },
      { char: '🏥', tags: ['hospital'] },
      { char: '🏦', tags: ['bank'] },
      { char: '🏨', tags: ['hotel'] },
      { char: '🏪', tags: ['convenience store'] },
      { char: '🏫', tags: ['school'] },
      { char: '🏬', tags: ['department store'] },
      { char: '🏭', tags: ['factory'] },
      { char: '🏯', tags: ['japanese castle'] },
      { char: '🏰', tags: ['castle'] },
      { char: '💒', tags: ['wedding'] },
      { char: '🗼', tags: ['tokyo tower'] },
      { char: '🗽', tags: ['statue of liberty'] },
    ],
  },
  {
    id: 'objects',
    title: 'Objects',
    icon: Lightbulb,
    emojis: [
      { char: '💡', tags: ['light bulb', 'idea'] },
      { char: '🔦', tags: ['flashlight'] },
      { char: '🕯️', tags: ['candle'] },
      { char: '🪔', tags: ['diya lamp'] },
      { char: '🏮', tags: ['red paper lantern'] },
      { char: '📱', tags: ['mobile phone', 'cellphone'] },
      { char: '📲', tags: ['mobile phone with arrow'] },
      { char: '💻', tags: ['laptop'] },
      { char: '🖥️', tags: ['desktop computer'] },
      { char: '🖨️', tags: ['printer'] },
      { char: '⌨️', tags: ['keyboard'] },
      { char: '🖱️', tags: ['computer mouse'] },
      { char: '💽', tags: ['computer disk'] },
      { char: '💾', tags: ['floppy disk'] },
      { char: '💿', tags: ['optical disk'] },
      { char: '📀', tags: ['dvd'] },
      { char: '📷', tags: ['camera', 'photo'] },
      { char: '📸', tags: ['camera with flash'] },
      { char: '📹', tags: ['video camera'] },
      { char: '🎥', tags: ['movie camera'] },
      { char: '📽️', tags: ['film projector'] },
      { char: '📺', tags: ['television', 'tv'] },
      { char: '📻', tags: ['radio'] },
      { char: '🎙️', tags: ['studio microphone'] },
      { char: '📞', tags: ['telephone receiver'] },
      { char: '📟', tags: ['pager'] },
      { char: '📠', tags: ['fax machine'] },
      { char: '🔋', tags: ['battery'] },
      { char: '🔌', tags: ['electric plug'] },
      { char: '💰', tags: ['money bag', 'cash', 'dollars'] },
      { char: '💵', tags: ['dollar banknote'] },
      { char: '🪙', tags: ['coin'] },
      { char: '💳', tags: ['credit card'] },
      { char: '💎', tags: ['gem stone', 'diamond'] },
      { char: '🛍️', tags: ['shopping bags'] },
      { char: '🛒', tags: ['shopping cart'] },
      { char: '🎁', tags: ['wrapped gift', 'present'] },
      { char: '🎈', tags: ['balloon'] },
      { char: '🎉', tags: ['party popper', 'tada'] },
      { char: '🎊', tags: ['confetti ball'] },
      { char: '📦', tags: ['package', 'box'] },
      { char: '🏷️', tags: ['label', 'tag'] },
      { char: '✉️', tags: ['envelope', 'mail'] },
      { char: '📧', tags: ['e-mail'] },
      { char: '📨', tags: ['incoming envelope'] },
      { char: '📩', tags: ['envelope with arrow'] },
      { char: '📯', tags: ['postal horn'] },
      { char: '📫', tags: ['closed mailbox with raised flag'] },
      { char: '📪', tags: ['closed mailbox with lowered flag'] },
      { char: '📬', tags: ['open mailbox with raised flag'] },
      { char: '📭', tags: ['open mailbox with lowered flag'] },
      { char: '📮', tags: ['postbox'] },
      { char: '📝', tags: ['memo', 'pencil', 'note'] },
      { char: '📁', tags: ['file folder'] },
      { char: '📂', tags: ['open file folder'] },
      { char: '📅', tags: ['calendar', 'date'] },
      { char: '📆', tags: ['tear-off calendar'] },
      { char: '📇', tags: ['card index'] },
      { char: '📈', tags: ['chart increasing', 'growth', 'trending'] },
      { char: '📉', tags: ['chart decreasing'] },
      { char: '📊', tags: ['bar chart'] },
      { char: '📋', tags: ['clipboard'] },
      { char: '📌', tags: ['pushpin', 'pin'] },
      { char: '📍', tags: ['round pushpin', 'location'] },
      { char: '📎', tags: ['paperclip'] },
      { char: '📏', tags: ['straight ruler'] },
      { char: '📐', tags: ['triangular ruler'] },
      { char: '✂️', tags: ['scissors'] },
      { char: '🔒', tags: ['locked'] },
      { char: '🔓', tags: ['unlocked'] },
      { char: '🔏', tags: ['locked with pen'] },
      { char: '🔐', tags: ['locked with key'] },
      { char: '🔑', tags: ['key'] },
      { char: '🗝️', tags: ['old key'] },
      { char: '🔨', tags: ['hammer'] },
      { char: '🪓', tags: ['axe'] },
      { char: '⛏️', tags: ['pick'] },
      { char: '🔧', tags: ['wrench'] },
      { char: '🪛', tags: ['screwdriver'] },
      { char: '🔩', tags: ['nut and bolt'] },
      { char: '⚙️', tags: ['gear'] },
      { char: '🧲', tags: ['magnet'] },
    ],
  },
  {
    id: 'symbols',
    title: 'Symbols',
    icon: AtSign,
    emojis: [
      { char: '❤️', tags: ['red heart', 'love'] },
      { char: '🧡', tags: ['orange heart'] },
      { char: '💛', tags: ['yellow heart'] },
      { char: '💚', tags: ['green heart'] },
      { char: '💙', tags: ['blue heart'] },
      { char: '💜', tags: ['purple heart'] },
      { char: '🖤', tags: ['black heart'] },
      { char: '🤍', tags: ['white heart'] },
      { char: '🤎', tags: ['brown heart'] },
      { char: '💔', tags: ['broken heart'] },
      { char: '❤️‍🔥', tags: ['heart on fire'] },
      { char: '❤️‍🩹', tags: ['mending heart'] },
      { char: '❣️', tags: ['heart exclamation'] },
      { char: '💕', tags: ['two hearts'] },
      { char: '💞', tags: ['revolving hearts'] },
      { char: '💓', tags: ['beating heart'] },
      { char: '💗', tags: ['growing heart'] },
      { char: '💖', tags: ['sparkling heart'] },
      { char: '💘', tags: ['heart with arrow'] },
      { char: '💝', tags: ['heart with ribbon'] },
      { char: '💟', tags: ['heart decoration'] },
      { char: '☮️', tags: ['peace symbol'] },
      { char: '✝️', tags: ['latin cross'] },
      { char: '☪️', tags: ['star and crescent'] },
      { char: '🕉️', tags: ['om'] },
      { char: '☸️', tags: ['wheel of dharma'] },
      { char: '✡️', tags: ['star of david'] },
      { char: '🔯', tags: ['six pointed star'] },
      { char: '🕎', tags: ['menorah'] },
      { char: '☯️', tags: ['yin yang'] },
      { char: '☦️', tags: ['orthodox cross'] },
      { char: '🛐', tags: ['place of worship'] },
      { char: '⛎', tags: ['ophiuchus'] },
      { char: '♈', tags: ['aries'] },
      { char: '♉', tags: ['taurus'] },
      { char: '♊', tags: ['gemini'] },
      { char: '♋', tags: ['cancer'] },
      { char: '♌', tags: ['leo'] },
      { char: '♍', tags: ['virgo'] },
      { char: '♎', tags: ['libra'] },
      { char: '♏', tags: ['scorpio'] },
      { char: '♐', tags: ['sagittarius'] },
      { char: '♑', tags: ['capricorn'] },
      { char: '♒', tags: ['aquarius'] },
      { char: '♓', tags: ['pisces'] },
      { char: '🆔', tags: ['id button'] },
      { char: '⚛️', tags: ['atom symbol'] },
      { char: '🈳', tags: ['japanese vacancy button'] },
      { char: '🈹', tags: ['japanese discount button'] },
      { char: '☢️', tags: ['radioactive'] },
      { char: '☣️', tags: ['biohazard'] },
      { char: '📴', tags: ['mobile phone off'] },
      { char: '📳', tags: ['vibration mode'] },
      { char: '🈶', tags: ['japanese not free of charge button'] },
      { char: '🈚', tags: ['japanese free of charge button'] },
      { char: '🈸', tags: ['japanese application button'] },
      { char: '🈺', tags: ['japanese open for business button'] },
      { char: '🉑', tags: ['japanese acceptable button'] },
      { char: '💮', tags: ['white flower'] },
      { char: '🉐', tags: ['japanese bargain button'] },
      { char: '㊙️', tags: ['japanese secret button'] },
      { char: '㊗️', tags: ['japanese congratulations button'] },
      { char: '🈴', tags: ['japanese passing grade button'] },
      { char: '🈵', tags: ['japanese no vacancy button'] },
      { char: '🈲', tags: ['japanese prohibited button'] },
      { char: '🅰️', tags: ['a button (blood type)'] },
      { char: '🅱️', tags: ['b button (blood type)'] },
      { char: '🆎', tags: ['ab button (blood type)'] },
      { char: '🆑', tags: ['cl button'] },
      { char: '🅾️', tags: ['o button (blood type)'] },
      { char: '🆘', tags: ['sos button'] },
      { char: '❌', tags: ['cross mark'] },
      { char: '⭕', tags: ['hollow red circle'] },
      { char: '🛑', tags: ['stop sign'] },
      { char: '⛔', tags: ['no entry'] },
      { char: '📛', tags: ['name badge'] },
      { char: '🚫', tags: ['prohibited'] },
      { char: '💯', tags: ['hundred points'] },
      { char: '💢', tags: ['anger symbol'] },
      { char: '♨️', tags: ['hot springs'] },
      { char: '🚷', tags: ['no pedestrians'] },
      { char: '🚯', tags: ['no littering'] },
      { char: '🚳', tags: ['no bicycles'] },
      { char: '🚱', tags: ['non-potable water'] },
      { char: '🔞', tags: ['no one under eighteen'] },
      { char: '📵', tags: ['no mobile phones'] },
      { char: '🚭', tags: ['no smoking'] },
      { char: '❗', tags: ['red exclamation mark'] },
      { char: '❕', tags: ['white exclamation mark'] },
      { char: '❓', tags: ['red question mark'] },
      { char: '❔', tags: ['white question mark'] },
      { char: '‼️', tags: ['double exclamation mark'] },
      { char: '⁉️', tags: ['exclamation question mark'] },
      { char: '🔅', tags: ['dim button'] },
      { char: '🔆', tags: ['bright button'] },
      { char: '〽️', tags: ['part alternation mark'] },
      { char: '⚠️', tags: ['warning'] },
      { char: '🚸', tags: ['children crossing'] },
      { char: '🔱', tags: ['trident emblem'] },
      { char: '⚜️', tags: ['fleur-de-lis'] },
      { char: '🔰', tags: ['japanese symbol for beginner'] },
      { char: '♻️', tags: ['recycling symbol'] },
      { char: '✅', tags: ['check mark button'] },
      { char: '🈯', tags: ['japanese reserved button'] },
      { char: '💹', tags: ['chart increasing with yen'] },
      { char: '❇️', tags: ['sparkle'] },
      { char: '✳️', tags: ['eight-spoked asterisk'] },
      { char: '❎', tags: ['cross mark button'] },
      { char: '🌐', tags: ['globe with meridians'] },
      { char: '💠', tags: ['diamond with a dot'] },
      { char: 'Ⓜ️', tags: ['circled m'] },
      { char: '🌀', tags: ['cyclone'] },
      { char: '💤', tags: ['zzz'] },
      { char: '🏧', tags: ['atm sign'] },
      { char: '🚾', tags: ['water closet', 'toilet', 'wc'] },
      { char: '♿', tags: ['wheelchair symbol'] },
      { char: '🅿️', tags: ['p button'] },
      { char: '🛗', tags: ['elevator'] },
      { char: '🈳', tags: ['japanese vacancy button'] },
      { char: '🈂️', tags: ['japanese service charge button'] },
      { char: '🛂', tags: ['passport control'] },
      { char: '🛃', tags: ['customs'] },
      { char: '🛄', tags: ['baggage claim'] },
      { char: '🛅', tags: ['left luggage'] },
      { char: '🚹', tags: ['men’s room'] },
      { char: '🚺', tags: ['women’s room'] },
      { char: '🚼', tags: ['baby symbol'] },
      { char: '⚧️', tags: ['transgender symbol'] },
      { char: '🚻', tags: ['restroom'] },
      { char: '🚮', tags: ['litter in bin sign'] },
      { char: '🎦', tags: ['cinema'] },
      { char: '📶', tags: ['antenna bars'] },
      { char: '🈁', tags: ['japanese here button'] },
      { char: '🆖', tags: ['ng button'] },
      { char: '🆗', tags: ['ok button'] },
      { char: '🆙', tags: ['up! button'] },
      { char: '🆒', tags: ['cool button'] },
      { char: '🆕', tags: ['new button'] },
      { char: '🆓', tags: ['free button'] },
      { char: '0️⃣', tags: ['keycap: 0'] },
      { char: '1️⃣', tags: ['keycap: 1'] },
      { char: '2️⃣', tags: ['keycap: 2'] },
      { char: '3️⃣', tags: ['keycap: 3'] },
      { char: '4️⃣', tags: ['keycap: 4'] },
      { char: '5️⃣', tags: ['keycap: 5'] },
      { char: '6️⃣', tags: ['keycap: 6'] },
      { char: '7️⃣', tags: ['keycap: 7'] },
      { char: '8️⃣', tags: ['keycap: 8'] },
      { char: '9️⃣', tags: ['keycap: 9'] },
      { char: '🔟', tags: ['keycap: 10'] },
      { char: '🔢', tags: ['input numbers'] },
      { char: '#️⃣', tags: ['keycap: #'] },
      { char: '*️⃣', tags: ['keycap: *'] },
      { char: '⏏️', tags: ['eject button'] },
      { char: '▶️', tags: ['play button'] },
      { char: '⏸️', tags: ['pause button'] },
      { char: '⏯️', tags: ['play or pause button'] },
      { char: '⏹️', tags: ['stop button'] },
      { char: '⏺️', tags: ['record button'] },
      { char: '⏭️', tags: ['next track button'] },
      { char: '⏮️', tags: ['last track button'] },
      { char: '⏩', tags: ['fast-forward button'] },
      { char: '⏪', tags: ['fast reverse button'] },
      { char: '⏫', tags: ['fast up button'] },
      { char: '⏬', tags: ['fast down button'] },
      { char: '◀️', tags: ['reverse button'] },
      { char: '🔼', tags: ['upwards button'] },
      { char: '🔽', tags: ['downwards button'] },
      { char: '➡️', tags: ['right arrow'] },
      { char: '⬅️', tags: ['left arrow'] },
      { char: '⬆️', tags: ['up arrow'] },
      { char: '⬇️', tags: ['down arrow'] },
      { char: '↗️', tags: ['up-right arrow'] },
      { char: '↘️', tags: ['down-right arrow'] },
      { char: '↙️', tags: ['down-left arrow'] },
      { char: '↖️', tags: ['up-left arrow'] },
      { char: '↕️', tags: ['up-down arrow'] },
      { char: '↔️', tags: ['left-right arrow'] },
      { char: '↪️', tags: ['left arrow curving right'] },
      { char: '↩️', tags: ['right arrow curving left'] },
      { char: '⤴️', tags: ['right arrow curving up'] },
      { char: '⤵️', tags: ['right arrow curving down'] },
      { char: '🔃', tags: ['clockwise vertical arrows'] },
      { char: '🔄', tags: ['counterclockwise arrows button'] },
      { char: '🔙', tags: ['back arrow'] },
      { char: '🔚', tags: ['end arrow'] },
      { char: '🔛', tags: ['on! arrow'] },
      { char: '🔜', tags: ['soon arrow'] },
      { char: '🔝', tags: ['top arrow'] },
    ],
  },
  {
    id: 'flags',
    title: 'Flags',
    icon: Flag,
    emojis: [
      { char: '🏁', tags: ['chequered flag'] },
      { char: '🚩', tags: ['triangular flag'] },
      { char: '🎌', tags: ['crossed flags'] },
      { char: '🏴', tags: ['black flag'] },
      { char: '🏳️', tags: ['white flag'] },
      { char: '🏳️‍🌈', tags: ['rainbow flag'] },
      { char: '🏳️‍⚧️', tags: ['transgender flag'] },
      { char: '🏴‍☠️', tags: ['pirate flag'] },
      { char: '🇰🇭', tags: ['cambodia', 'khmer flag'] },
      { char: '🇺🇸', tags: ['united states', 'usa flag'] },
      { char: '🇬🇧', tags: ['united kingdom', 'uk flag'] },
      { char: '🇫🇷', tags: ['france flag'] },
      { char: '🇩🇪', tags: ['germany flag'] },
      { char: '🇯🇵', tags: ['japan flag'] },
      { char: '🇰🇷', tags: ['south korea flag'] },
      { char: '🇨🇳', tags: ['china flag'] },
      { char: '🇻🇳', tags: ['vietnam flag'] },
      { char: '🇹🇭', tags: ['thailand flag'] },
      { char: '🇸🇬', tags: ['singapore flag'] },
      { char: '🇲🇾', tags: ['malaysia flag'] },
      { char: '🇵🇭', tags: ['philippines flag'] },
      { char: '🇮🇩', tags: ['indonesia flag'] },
      { char: '🇦🇺', tags: ['australia flag'] },
      { char: '🇨🇦', tags: ['canada flag'] },
      { char: '🇮🇳', tags: ['india flag'] },
      { char: '🇧🇷', tags: ['brazil flag'] },
    ],
  },
];

export const MetaEmojiPicker = ({ onSelectEmoji, onClose }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('smileys');
  const [recentList, setRecentList] = useState(() => {
    try {
      const saved = localStorage.getItem('meta_recent_emojis');
      return saved ? JSON.parse(saved) : DEFAULT_RECENT;
    } catch {
      return DEFAULT_RECENT;
    }
  });

  const pickerRef = useRef(null);
  const scrollContainerRef = useRef(null);
  const sectionRefs = useRef({});

  // Close on outside click
  useEffect(() => {
    const handleOutside = (e) => {
      if (pickerRef.current && !pickerRef.current.contains(e.target)) {
        onClose();
      }
    };
    document.addEventListener('mousedown', handleOutside);
    return () => document.removeEventListener('mousedown', handleOutside);
  }, [onClose]);

  const handleCategoryTabClick = (categoryId) => {
    setActiveCategory(categoryId);
    setSearchQuery('');
    const targetEl = sectionRefs.current[categoryId];
    if (targetEl && scrollContainerRef.current) {
      scrollContainerRef.current.scrollTop = targetEl.offsetTop - 50;
    }
  };

  const handlePickEmoji = (emojiChar) => {
    onSelectEmoji(emojiChar);
    setRecentList((prev) => {
      const next = [emojiChar, ...prev.filter((c) => c !== emojiChar)].slice(0, 16);
      try {
        localStorage.setItem('meta_recent_emojis', JSON.stringify(next));
      } catch {}
      return next;
    });
  };

  // Build category list with dynamic recently used
  const categoriesToRender = EMOJI_CATEGORIES.map((cat) => {
    if (cat.id === 'recent') {
      return {
        ...cat,
        emojis: recentList.map((c) => ({ char: c, tags: ['recent'] })),
      };
    }
    return cat;
  });

  const filteredCategories = categoriesToRender.map((cat) => {
    if (!searchQuery.trim()) return cat;
    const query = searchQuery.toLowerCase().trim();
    const matching = cat.emojis.filter(
      (e) => e.char.includes(query) || e.tags.some((t) => t.includes(query))
    );
    return { ...cat, emojis: matching };
  }).filter((cat) => cat.emojis.length > 0);

  return (
    <div className="meta-emoji-popover" ref={pickerRef} onClick={(e) => e.stopPropagation()}>
      {/* ── Top Search Bar ── */}
      <div className="meta-emoji-search-bar">
        <Search size={15} className="meta-emoji-search-icon" />
        <input
          type="text"
          placeholder="Search emojis"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="meta-emoji-search-input"
          autoFocus
        />
        {searchQuery && (
          <button
            type="button"
            className="meta-emoji-clear-btn"
            onClick={() => setSearchQuery('')}
            title="Clear"
          >
            <X size={13} />
          </button>
        )}
      </div>

      {/* ── Emojis Scrollable Content Grid ── */}
      <div className="meta-emoji-scroll-content" ref={scrollContainerRef}>
        {filteredCategories.length === 0 ? (
          <div className="meta-emoji-empty">No emojis found</div>
        ) : (
          filteredCategories.map((cat) => (
            <div
              key={cat.id}
              className="meta-emoji-section"
              ref={(el) => (sectionRefs.current[cat.id] = el)}
            >
              <div className="meta-emoji-section-title">{cat.title}</div>
              <div className="meta-emoji-grid">
                {cat.emojis.map((item, idx) => (
                  <button
                    key={`${cat.id}-${idx}`}
                    type="button"
                    className="meta-emoji-item-btn"
                    onClick={() => handlePickEmoji(item.char)}
                    title={item.tags[0] || 'Emoji'}
                  >
                    {item.char}
                  </button>
                ))}
              </div>
            </div>
          ))
        )}
      </div>

      {/* ── Bottom Category Switcher Tabs (Matches Meta Exactly) ── */}
      <div className="meta-emoji-category-bar">
        {EMOJI_CATEGORIES.map((cat) => {
          const IconComp = cat.icon;
          const isActive = activeCategory === cat.id && !searchQuery;
          return (
            <button
              key={cat.id}
              type="button"
              className={`meta-emoji-cat-tab ${isActive ? 'active' : ''}`}
              onClick={() => handleCategoryTabClick(cat.id)}
              title={cat.title}
            >
              <IconComp size={16} />
              {isActive && <div className="meta-emoji-cat-indicator" />}
            </button>
          );
        })}
      </div>
    </div>
  );
};
